
// This file was auto-generated by ML.NET Model Builder. 

using Qualytics_L0_ConsoleApp;

// Create single instance of sample data from first line of dataset for model input
L0.ModelInput sampleData = new L0.ModelInput()
{
    Translated_Short_Description = @"Preventive maintenance: server reboot action",
    Translated_Description = @"Scheduled server reboot action due to server uptime higher than 300 days",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual L0_Level with predicted L0_Level from sample data...\n\n");


Console.WriteLine($"L0_Level: {@"Hardware"}");
Console.WriteLine($"Translated_Short_Description: {@"Preventive maintenance: server reboot action"}");
Console.WriteLine($"Translated_Description: {@"Scheduled server reboot action due to server uptime higher than 300 days"}");


var sortedScoresWithLabel = L0.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

