
// This file was auto-generated by ML.NET Model Builder. 

using Qualytics_L3_ConsoleApp;

// Create single instance of sample data from first line of dataset for model input
L3.ModelInput sampleData = new L3.ModelInput()
{
    L0_Level = @"Hardware",
    Reported_Problem_Code_L1 = @"Device, System or Product Hardware",
    Reported_Problem_Code_L2 = @"Computers, workstations, & servers (damaged, not functioning)",
    Translated_Short_Description = @"Preventive maintenance: server reboot action",
    Translated_Description = @"Scheduled server reboot action due to server uptime higher than 300 days",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Reported_Problem_Code_L3 with predicted Reported_Problem_Code_L3 from sample data...\n\n");


Console.WriteLine($"L0_Level: {@"Hardware"}");
Console.WriteLine($"Reported_Problem_Code_L1: {@"Device, System or Product Hardware"}");
Console.WriteLine($"Reported_Problem_Code_L2: {@"Computers, workstations, & servers (damaged, not functioning)"}");
Console.WriteLine($"Reported_Problem_Code_L3: {@"Physically damaged, deformed or not functioning"}");
Console.WriteLine($"Translated_Short_Description: {@"Preventive maintenance: server reboot action"}");
Console.WriteLine($"Translated_Description: {@"Scheduled server reboot action due to server uptime higher than 300 days"}");


var sortedScoresWithLabel = L3.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

